#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/X00TD

PRODUCT_COPY_FILES += \
    vendor/asus/X00TD/proprietary/product/etc/permissions/qti_fingerprint_interface.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/qti_fingerprint_interface.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/cdma_call_conf.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/cdma_call_conf.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/RemoteSimlock.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/RemoteSimlock.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/RemoteSimlockManager.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/RemoteSimlockManager.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/UimGba.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/UimGba.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/UimGbaManager.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/UimGbaManager.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/UimService.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/UimService.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/audiosphere.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/com.qualcomm.qcrilmsgtunnel.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qcrilmsgtunnel.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.0-java.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.1-java.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.imscmservice-V2.2-java.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/lpa.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/lpa.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/org_codeaurora_ims.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/org_codeaurora_ims.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/uimremoteclient.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/uimremoteclient.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/permissions/uimremoteserver.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/uimremoteserver.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/spn-conf.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/spn-conf.xml \
    vendor/asus/X00TD/proprietary/system_ext/etc/sysconfig/qti_whitelist_system_ext.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/sysconfig/qti_whitelist_system_ext.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/asus/X00TD/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/gc5025_ofilm_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5025_ofilm_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/gc5025_ofilm_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5025_ofilm_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi1333_ofilm_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi1333_ofilm_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi556_holitech_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi556_holitech_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi556_holitech_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi556_holitech_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi846_kingcome_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi846_kingcome_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/hi846_tsp_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/hi846_tsp_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov13855_chicony_rear_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_chicony_rear_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov13855_holitech_13m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov13855_holitech_13m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16880_qtech_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16880_qtech_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16885_holitech_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_holitech_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov16885_ofilm_16m_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov16885_ofilm_16m_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/camera/ov8856_chicony_front_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ov8856_chicony_front_chromatix.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.adsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.2-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/asus/X00TD/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/commonsysnodesconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonsysnodesconfigs.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/powerhint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerhint.xml \
    vendor/asus/X00TD/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/asus/X00TD/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/asus/X00TD/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/asus/X00TD/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.elf \
    vendor/asus/X00TD/proprietary/vendor/firmware/a512_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a512_zap.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/apbtfw10.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/apbtfw10.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/apbtfw11.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/apbtfw11.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/apnv10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/apnv10.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/apnv11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/apnv11.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.102:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.102 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.104:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.104 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.105:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.105 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.106:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.106 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.107:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.107 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.108:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.108 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.109:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.109 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0a:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0a \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0b:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0b \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0d:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0d \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0e:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0e \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b0f:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b0f \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b30:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b30 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b31:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b31 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b32:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b32 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b33:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b33 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b34:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b34 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b35:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b35 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b36:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b36 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.b37:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.b37 \
    vendor/asus/X00TD/proprietary/vendor/firmware/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bdwlan.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cdfinger.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cdfinger.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/cmnlib64.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cmnlib64.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b08 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b19 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b22 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b24 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b26 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b28:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b28 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.b29:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.b29 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9335.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9335.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b13 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b15 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpe_9340.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cpe_9340.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/cppf.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cppf.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw11.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw11.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw20.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crbtfw21.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/crbtfw21.tlv \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv11.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv20.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/crnv21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/crnv21.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/data.msc \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/dhsecapp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/dhsecapp.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/fp998eas.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fp998eas.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/goodixfp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/goodixfp.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/gptest.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/gptest.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/haventkn.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/haventkn.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/hyp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/hyp.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/iris.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/iris.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/isdbtmm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/isdbtmm.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/mba.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/mba.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/mdtpseca.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/mdtpseca.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b08 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b09 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b10 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b11 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b12 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b13 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b14 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b16 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b17 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b18 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b20 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b21 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b22 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b23:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b23 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b24 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b25:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b25 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b26 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b27:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b27 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.b28:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.b28 \
    vendor/asus/X00TD/proprietary/vendor/firmware/modem.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/modem.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/modemuw.jsn:$(TARGET_COPY_OUT_VENDOR)/firmware/modemuw.jsn \
    vendor/asus/X00TD/proprietary/vendor/firmware/novatek_ts_fw_dj.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_dj.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/novatek_ts_fw_txd.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_txd.bin \
    vendor/asus/X00TD/proprietary/vendor/firmware/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn553_fw.so \
    vendor/asus/X00TD/proprietary/vendor/firmware/pmic.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/pmic.elf \
    vendor/asus/X00TD/proprietary/vendor/firmware/qdsp6m.qdb:$(TARGET_COPY_OUT_VENDOR)/firmware/qdsp6m.qdb \
    vendor/asus/X00TD/proprietary/vendor/firmware/rpm.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/rpm.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/securemm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/securemm.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap32.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap32.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/smplap64.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/smplap64.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b00 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b01 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b02 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b03 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b04 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b05 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b06 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.b07 \
    vendor/asus/X00TD/proprietary/vendor/firmware/widevine.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/widevine.mdt \
    vendor/asus/X00TD/proprietary/vendor/firmware/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp.mbn \
    vendor/asus/X00TD/proprietary/vendor/firmware/xbl.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/xbl.elf \
    vendor/asus/X00TD/proprietary/vendor/lib/dualcali_dump.bin:$(TARGET_COPY_OUT_VENDOR)/lib/dualcali_dump.bin \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/11_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/11_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    vendor/asus/X00TD/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    sensors.sdm660_64 \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libGPreqcancel_svc \
    libOpenCL \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libVkLayer_q3dtools \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudioparsers \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libdapparamstorage \
    libdiag \
    libfastcvadsp_stub \
    libfastrpc_utf_stub \
    libgpudataproducer \
    libgsl \
    libhdr_tm \
    libidl \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libllvm-glnext \
    libllvm-qcom \
    libmdmdetect \
    libmdsprpc \
    libmmosal \
    libperfconfig \
    libperfgluelayer \
    libperfioctl \
    libperipheral_client \
    libqcbor \
    libqmi_cci \
    libqmi_common_so \
    libqmi_encdec \
    libqmiservices \
    libqseed3 \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensor1 \
    libsensor_reg \
    libsubsystem_control \
    libsysmon_cdsp_skel \
    libthermalclient \
    libtinyxml2_1 \
    sensors.native \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    libspatialaudio \
    vendor.dolby.hardware.dms@2.0 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.memory.pasrmanager@1.0 \
    vendor.qti.memory.pasrmanager@1.1 \
    libAlacSwDec \
    libApeSwDec \
    libFlacSwDec \
    libOmxAacDec \
    libOmxAlacDec \
    libOmxAlacDecSw \
    libOmxAmrDec \
    libOmxAmrwbplusDec \
    libOmxApeDec \
    libOmxApeDecSw \
    libOmxDsdDec \
    libOmxEvrcDec \
    libOmxG711Dec \
    libOmxQcelp13Dec \
    libOmxWmaDec \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libadpcmdec \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libdeccfg \
    libdrc \
    libdsd2pcm \
    libfastcvopt \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libhdmipassthru \
    libqtigef \
    libsmwrapper \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libswdap \
    libswgamedap \
    libswvqe \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0_vendor \
    com.qualcomm.qti.imscmservice@2.1_vendor \
    com.qualcomm.qti.imscmservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.0_vendor \
    com.qualcomm.qti.uceservice@2.1_vendor \
    com.qualcomm.qti.uceservice@2.2_vendor \
    com.qualcomm.qti.uceservice@2.3_vendor \
    deviceInfoServiceModule \
    android.hardware.bluetooth@1.0-impl-qti \
    com.dsi.ant@1.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.qccvndhal@1.0-impl \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libGPreqcancel \
    libaoa \
    libasn1cper \
    libasn1crt \
    libasn1crtx \
    libbase64 \
    libbt-hidlclient \
    libbtnv \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libcpion \
    libdataitems \
    libdlbdsservice \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdsutils \
    libgdtap \
    libgnsspps \
    libhdcpsrm \
    libizat_core \
    libjnihelper \
    liblbs_core \
    libloc_api_v02 \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libminkdescriptor \
    libminksocket \
    libmm-hdcpmgr \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    liboemcrypto \
    libpdmapper \
    libpdnotifier \
    libqcc_file_agent \
    libqcci_legacy \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdi \
    libqdp \
    libqisl \
    libqmi \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_csi \
    libqmi_legacy \
    libqrtr \
    libqsocket \
    librcc \
    libril-qc-hal-qmi \
    libril-qc-logger \
    librilqmiservices \
    librmp \
    librpmb \
    libsmemlog \
    libssd \
    libsystem_health_mon \
    libtime_genoff \
    libtzdrmgenprov \
    libwms \
    libwqe \
    libwvhidl \
    libxml \
    libxtadapter \
    libxtwifi_server_protocol \
    libxtwifi_server_protocol_uri_v3 \
    qcrilHalMarshal \
    qcril_hal_client \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.qti.data.factory@2.0_vendor \
    vendor.qti.data.factory@2.1_vendor \
    vendor.qti.data.factory@2.2_vendor \
    vendor.qti.data.factory@2.3_vendor \
    vendor.qti.data.mwqem@1.0_vendor \
    vendor.qti.data.mwqemaidlservice-V1-ndk_vendor \
    vendor.qti.data.slm@1.0_vendor \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.constants@1.0_vendor \
    vendor.qti.hardware.data.cne.internal.server@1.0_vendor \
    vendor.qti.hardware.data.connection@1.0_vendor \
    vendor.qti.hardware.data.connection@1.1_vendor \
    vendor.qti.hardware.data.dynamicdds@1.0_vendor \
    vendor.qti.hardware.data.dynamicdds@1.1_vendor \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-ndk_vendor \
    vendor.qti.hardware.data.flow@1.0_vendor \
    vendor.qti.hardware.data.flow@1.1_vendor \
    vendor.qti.hardware.data.flowaidlservice-V1-ndk_vendor \
    vendor.qti.hardware.data.iwlan@1.0_vendor \
    vendor.qti.hardware.data.latency@1.0_vendor \
    vendor.qti.hardware.data.lce@1.0_vendor \
    vendor.qti.hardware.data.lceaidlservice-V1-ndk_vendor \
    vendor.qti.hardware.data.qmi@1.0_vendor \
    vendor.qti.hardware.fm@1.0_vendor \
    vendor.qti.hardware.mwqemadapter@1.0_vendor \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qccvndhal@1.0-halimpl \
    vendor.qti.hardware.qccvndhal@1.0 \
    vendor.qti.hardware.radio.am@1.0_vendor \
    vendor.qti.hardware.radio.ims@1.0_vendor \
    vendor.qti.hardware.radio.ims@1.1_vendor \
    vendor.qti.hardware.radio.ims@1.2_vendor \
    vendor.qti.hardware.radio.ims@1.3_vendor \
    vendor.qti.hardware.radio.ims@1.4_vendor \
    vendor.qti.hardware.radio.ims@1.5_vendor \
    vendor.qti.hardware.radio.ims@1.6_vendor \
    vendor.qti.hardware.radio.ims@1.7_vendor \
    vendor.qti.hardware.radio.ims@1.8_vendor \
    vendor.qti.hardware.radio.ims@1.9_vendor \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0_vendor \
    vendor.qti.hardware.radio.lpa@1.0_vendor \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.lpa@1.2 \
    vendor.qti.hardware.radio.qcrilhook@1.0_vendor \
    vendor.qti.hardware.radio.qtiradio@1.0_vendor \
    vendor.qti.hardware.radio.qtiradio@2.0_vendor \
    vendor.qti.hardware.radio.qtiradio@2.1_vendor \
    vendor.qti.hardware.radio.qtiradio@2.2_vendor \
    vendor.qti.hardware.radio.qtiradio@2.3_vendor \
    vendor.qti.hardware.radio.qtiradio@2.4_vendor \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.qtiradio@2.6 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.uim@1.0_vendor \
    vendor.qti.hardware.radio.uim@1.1_vendor \
    vendor.qti.hardware.radio.uim@1.2_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.0_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.1_vendor \
    vendor.qti.hardware.radio.uim_remote_client@1.2_vendor \
    vendor.qti.hardware.radio.uim_remote_server@1.0_vendor \
    vendor.qti.hardware.slmadapter@1.0_vendor \
    vendor.qti.ims.callcapability@1.0_vendor \
    vendor.qti.ims.callinfo@1.0_vendor \
    vendor.qti.ims.factory@1.0_vendor \
    vendor.qti.ims.factory@1.1_vendor \
    vendor.qti.ims.rcsconfig@1.0_vendor \
    vendor.qti.ims.rcsconfig@1.1_vendor \
    vendor.qti.ims.rcsconfig@2.0_vendor \
    vendor.qti.ims.rcsconfig@2.1_vendor \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.latency@2.0_vendor \
    vendor.qti.latency@2.1_vendor \
    vendor.qti.latency@2.2_vendor \
    vendor.qti.latencyaidlservice-V1-ndk_vendor \
    libFastRPC_AUE_Forward_skel \
    libFastRPC_UTF_Forward_800h_skel \
    libFastRPC_UTF_Forward_Qtc2_skel \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    libhexagon_nn_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libvpp_svc_skel \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    com.quicinc.cne.server@1.0 \
    com.quicinc.cne.server@2.0 \
    com.quicinc.cne.server@2.1 \
    com.quicinc.cne.server@2.2 \
    fm_helium \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libembmsmmosal \
    libembmsmmparser_lite \
    libembmssqlite \
    libembmstinyxml \
    libfm-hci \
    libimscamera_jni \
    libimsmedia_jni \
    libmwqemiptablemgr \
    libqmi_cci_system \
    libqmi_encdec_system \
    vendor.qti.ImsRtpService-V1-ndk \
    vendor.qti.data.factory@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.factory@2.4 \
    vendor.qti.data.factory@2.5 \
    vendor.qti.data.factoryservice-V1-ndk \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.mwqemaidlservice-V1-ndk \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.1 \
    vendor.qti.hardware.data.cne.internal.server@1.2 \
    vendor.qti.hardware.data.cneaidlservice.internal.api-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.constants-V1-ndk \
    vendor.qti.hardware.data.cneaidlservice.internal.server-V1-ndk \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.dynamicdds@1.1 \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-ndk \
    vendor.qti.hardware.data.flow@1.0 \
    vendor.qti.hardware.data.flow@1.1 \
    vendor.qti.hardware.data.flowaidlservice-V1-ndk \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.iwlan@1.1 \
    vendor.qti.hardware.data.iwlandata-V1-ndk \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.lceaidlservice-V1-ndk \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.data.qmiaidlservice-V1-ndk \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.mwqemadapteraidlservice-V1-ndk \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.ims@1.8 \
    vendor.qti.hardware.radio.ims@1.9 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callcapabilityaidlservice-V1-ndk \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.configaidlservice-V1-ndk \
    vendor.qti.ims.configservice@1.0 \
    vendor.qti.ims.configservice@1.1 \
    vendor.qti.ims.connection@1.0 \
    vendor.qti.ims.connectionaidlservice-V1-ndk \
    vendor.qti.ims.datachannelservice-V1-ndk \
    vendor.qti.ims.datachannelservice-V2-ndk \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.factory@2.0 \
    vendor.qti.ims.factory@2.1 \
    vendor.qti.ims.factory@2.2 \
    vendor.qti.ims.factoryaidlservice-V1-ndk \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.ims.rcssip@1.0 \
    vendor.qti.ims.rcssip@1.1 \
    vendor.qti.ims.rcssip@1.2 \
    vendor.qti.ims.rcssipaidlservice-V1-ndk \
    vendor.qti.ims.rcsuce@1.0 \
    vendor.qti.ims.rcsuce@1.1 \
    vendor.qti.ims.rcsuce@1.2 \
    vendor.qti.ims.rcsuceaidlservice-V1-ndk \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.imsrtpservice@3.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vendor.qti.latency@2.2 \
    vendor.qti.latencyaidlservice-V1-ndk \
    CACertService \
    CneApp \
    IWlanService \
    TimeService \
    DeviceStatisticsService \
    QtiTelephonyService \
    datastatusnotification \
    remoteSimLockAuthentication \
    remotesimlockservice \
    uceShimService \
    uimgbaservice \
    uimlpaservice \
    uimremoteclient \
    uimremoteserver \
    xdivert \
    ims \
    qcrilmsgtunnel \
    tcmclient \
    ActivityExt \
    audiosphere \
    com.qti.dpmframework \
    com.qualcomm.qti.imscmservice-V2.0-java \
    com.qualcomm.qti.imscmservice-V2.1-java \
    com.qualcomm.qti.imscmservice-V2.2-java \
    com.qualcomm.qti.uceservice-V2.0-java \
    com.qualcomm.qti.uceservice-V2.1-java \
    com.qualcomm.qti.uceservice-V2.2-java \
    com.qualcomm.qti.uceservice-V2.3-java \
    com.quicinc.cne.api-V1.0-java \
    com.quicinc.cne.api-V1.1-java \
    com.quicinc.cne.constants-V1.0-java \
    com.quicinc.cne.constants-V2.0-java \
    com.quicinc.cne.constants-V2.1-java \
    dpmapi \
    qcrilhook \
    qti-telephony-common \
    remotesimlockmanagerlibrary \
    uimgbalibrary \
    uimgbamanagerlibrary \
    uimlpalibrary \
    uimremoteclientlibrary \
    uimremoteserverlibrary \
    uimremotesimlocklibrary \
    uimservicelibrary \
    vendor.qti.data.factory-V1.0-java \
    vendor.qti.data.factory-V2.0-java \
    vendor.qti.data.factory-V2.1-java \
    vendor.qti.data.factory-V2.2-java \
    vendor.qti.data.factory-V2.3-java \
    vendor.qti.data.factory-V2.4-java \
    vendor.qti.data.factory-V2.5-java \
    vendor.qti.data.factoryservice-V1-java \
    vendor.qti.data.mwqem-V1.0-java \
    vendor.qti.data.mwqemaidlservice-V1-java \
    vendor.qti.data.slm-V1.0-java \
    vendor.qti.hardware.data.cne.internal.api-V1.0-java \
    vendor.qti.hardware.data.cne.internal.constants-V1.0-java \
    vendor.qti.hardware.data.cne.internal.server-V1.0-java \
    vendor.qti.hardware.data.cne.internal.server-V1.1-java \
    vendor.qti.hardware.data.cne.internal.server-V1.2-java \
    vendor.qti.hardware.data.cneaidlservice.internal.api-V1-java \
    vendor.qti.hardware.data.cneaidlservice.internal.constants-V1-java \
    vendor.qti.hardware.data.cneaidlservice.internal.server-V1-java \
    vendor.qti.hardware.data.connection-V1.0-java \
    vendor.qti.hardware.data.connection-V1.1-java \
    vendor.qti.hardware.data.connectionfactory-V1-java \
    vendor.qti.hardware.data.dataactivity-V1-java \
    vendor.qti.hardware.data.dynamicdds-V1.0-java \
    vendor.qti.hardware.data.dynamicdds-V1.1-java \
    vendor.qti.hardware.data.dynamicddsaidlservice-V1-java \
    vendor.qti.hardware.data.flow-V1.0-java \
    vendor.qti.hardware.data.flow-V1.1-java \
    vendor.qti.hardware.data.flowaidlservice-V1-java \
    vendor.qti.hardware.data.iwlan-V1.0-java \
    vendor.qti.hardware.data.iwlan-V1.1-java \
    vendor.qti.hardware.data.iwlandata-V1-java \
    vendor.qti.hardware.data.ka-V1-java \
    vendor.qti.hardware.data.latency-V1.0-java \
    vendor.qti.hardware.data.lce-V1.0-java \
    vendor.qti.hardware.data.lceaidlservice-V1-java \
    vendor.qti.hardware.data.qmi-V1.0-java \
    vendor.qti.hardware.data.qmiaidlservice-V1-java \
    vendor.qti.hardware.mwqemadapter-V1.0-java \
    vendor.qti.hardware.mwqemadapteraidlservice-V1-java \
    vendor.qti.hardware.slmadapter-V1.0-java \
    vendor.qti.ims.callcapability-V1.0-java \
    vendor.qti.ims.callcapabilityaidlservice-V1-java \
    vendor.qti.ims.callinfo-V1.0-java \
    vendor.qti.ims.configaidlservice-V1-java \
    vendor.qti.ims.configservice-V1.0-java \
    vendor.qti.ims.configservice-V1.1-java \
    vendor.qti.ims.connection-V1.0-java \
    vendor.qti.ims.connectionaidlservice-V1-java \
    vendor.qti.ims.datachannelservice-V1-java \
    vendor.qti.ims.datachannelservice-V2-java \
    vendor.qti.ims.factory-V1.0-java \
    vendor.qti.ims.factory-V1.1-java \
    vendor.qti.ims.factory-V2.0-java \
    vendor.qti.ims.factory-V2.1-java \
    vendor.qti.ims.factory-V2.2-java \
    vendor.qti.ims.factoryaidlservice-V1-java \
    vendor.qti.ims.rcsconfig-V1.0-java \
    vendor.qti.ims.rcsconfig-V1.1-java \
    vendor.qti.ims.rcsconfig-V2.0-java \
    vendor.qti.ims.rcsconfig-V2.1-java \
    vendor.qti.ims.rcssip-V1.0-java \
    vendor.qti.ims.rcssip-V1.1-java \
    vendor.qti.ims.rcssip-V1.2-java \
    vendor.qti.ims.rcssipaidlservice-V1-java \
    vendor.qti.ims.rcsuce-V1.0-java \
    vendor.qti.ims.rcsuce-V1.1-java \
    vendor.qti.ims.rcsuce-V1.2-java \
    vendor.qti.ims.rcsuceaidlservice-V1-java \
    vendor.qti.latency-V2.0-java \
    vendor.qti.latency-V2.1-java \
    vendor.qti.latency-V2.2-java \
    vendor.qti.latencyaidlservice-V1-java \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    manifest_vendor.dolby.hardware.dms.xml \
    adpl \
    adsprpcd \
    cnd \
    cnss-daemon \
    dspservice \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    qcrild \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.perf@2.2-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    loc_launcher \
    lowi-server \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    qrtr-cfg \
    qrtr-ns \
    qseecomd \
    qti \
    rmt_storage \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    tftp_server \
    time_daemon \
    xtra-daemon \
    sensors.ssc \
    vendor.qti.hardware.fingerprint@1.0 \
    libactuator_hi1333_ofilm_dw9714v \
    libactuator_ov13855_chicony_rear_s2034 \
    libactuator_ov13855_holitech_fp5510a \
    libactuator_ov16880_qtech_rear_dw9714a \
    libactuator_ov16885_holitech_16m_fp5510a \
    libactuator_ov16885_ofilm_16m_dw9714v \
    libarcsoft_dualcam_refocus \
    libchromatix_gc5025_ofilm_13m_common \
    libchromatix_gc5025_ofilm_13m_cpp_ds_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_120 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_60 \
    libchromatix_gc5025_ofilm_13m_cpp_hfr_90 \
    libchromatix_gc5025_ofilm_13m_cpp_liveshot \
    libchromatix_gc5025_ofilm_13m_cpp_preview \
    libchromatix_gc5025_ofilm_13m_cpp_snapshot \
    libchromatix_gc5025_ofilm_13m_cpp_us_chromatix \
    libchromatix_gc5025_ofilm_13m_cpp_video \
    libchromatix_gc5025_ofilm_13m_cpp_video_full \
    libchromatix_gc5025_ofilm_13m_default_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_default_video \
    libchromatix_gc5025_ofilm_13m_default_video_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_120 \
    libchromatix_gc5025_ofilm_13m_hfr_120_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_60 \
    libchromatix_gc5025_ofilm_13m_hfr_60_bu64297 \
    libchromatix_gc5025_ofilm_13m_hfr_90 \
    libchromatix_gc5025_ofilm_13m_hfr_90_bu64297 \
    libchromatix_gc5025_ofilm_13m_postproc \
    libchromatix_gc5025_ofilm_13m_preview \
    libchromatix_gc5025_ofilm_13m_snapshot \
    libchromatix_gc5025_ofilm_13m_video_full \
    libchromatix_gc5025_ofilm_13m_zsl_preview_bu64297 \
    libchromatix_gc5025_ofilm_13m_zsl_video_bu64297 \
    libchromatix_gc5025_ofilm_16m_common \
    libchromatix_gc5025_ofilm_16m_cpp_ds_chromatix \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_120 \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_60 \
    libchromatix_gc5025_ofilm_16m_cpp_hfr_90 \
    libchromatix_gc5025_ofilm_16m_cpp_liveshot \
    libchromatix_gc5025_ofilm_16m_cpp_preview \
    libchromatix_gc5025_ofilm_16m_cpp_snapshot \
    libchromatix_gc5025_ofilm_16m_cpp_us_chromatix \
    libchromatix_gc5025_ofilm_16m_cpp_video \
    libchromatix_gc5025_ofilm_16m_cpp_video_full \
    libchromatix_gc5025_ofilm_16m_default_preview_bu64297 \
    libchromatix_gc5025_ofilm_16m_default_video \
    libchromatix_gc5025_ofilm_16m_default_video_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_120 \
    libchromatix_gc5025_ofilm_16m_hfr_120_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_60 \
    libchromatix_gc5025_ofilm_16m_hfr_60_bu64297 \
    libchromatix_gc5025_ofilm_16m_hfr_90 \
    libchromatix_gc5025_ofilm_16m_hfr_90_bu64297 \
    libchromatix_gc5025_ofilm_16m_postproc \
    libchromatix_gc5025_ofilm_16m_preview \
    libchromatix_gc5025_ofilm_16m_snapshot \
    libchromatix_gc5025_ofilm_16m_video_full \
    libchromatix_gc5025_ofilm_16m_zsl_preview_bu64297 \
    libchromatix_gc5025_ofilm_16m_zsl_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_common \
    libchromatix_hi1333_ofilm_13m_cpp_ds_chromatix \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_120 \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_60 \
    libchromatix_hi1333_ofilm_13m_cpp_hfr_90 \
    libchromatix_hi1333_ofilm_13m_cpp_liveshot \
    libchromatix_hi1333_ofilm_13m_cpp_preview \
    libchromatix_hi1333_ofilm_13m_cpp_snapshot \
    libchromatix_hi1333_ofilm_13m_cpp_us_chromatix \
    libchromatix_hi1333_ofilm_13m_cpp_video \
    libchromatix_hi1333_ofilm_13m_cpp_video_full \
    libchromatix_hi1333_ofilm_13m_default_preview_bu64297 \
    libchromatix_hi1333_ofilm_13m_default_video \
    libchromatix_hi1333_ofilm_13m_default_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_eis_video_bu64297 \
    libchromatix_hi1333_ofilm_13m_hdr \
    libchromatix_hi1333_ofilm_13m_hdr_cpp \
    libchromatix_hi1333_ofilm_13m_hdr_video_3a \
    libchromatix_hi1333_ofilm_13m_hfr_120 \
    libchromatix_hi1333_ofilm_13m_hfr_120_bu64297 \
    libchromatix_hi1333_ofilm_13m_hfr_60 \
    libchromatix_hi1333_ofilm_13m_hfr_60_bu64297 \
    libchromatix_hi1333_ofilm_13m_hfr_90 \
    libchromatix_hi1333_ofilm_13m_hfr_90_bu64297 \
    libchromatix_hi1333_ofilm_13m_postproc \
    libchromatix_hi1333_ofilm_13m_preview \
    libchromatix_hi1333_ofilm_13m_snapshot \
    libchromatix_hi1333_ofilm_13m_video_full \
    libchromatix_hi1333_ofilm_13m_zsl_preview_bu64297 \
    libchromatix_hi1333_ofilm_13m_zsl_video_bu64297 \
    libchromatix_hi556_holitech_13m_a3_default_preview \
    libchromatix_hi556_holitech_13m_a3_default_video \
    libchromatix_hi556_holitech_13m_a3_hfr_120 \
    libchromatix_hi556_holitech_13m_a3_hfr_60 \
    libchromatix_hi556_holitech_13m_a3_hfr_90 \
    libchromatix_hi556_holitech_13m_common \
    libchromatix_hi556_holitech_13m_cpp_ds_chromatix \
    libchromatix_hi556_holitech_13m_cpp_hfr_120 \
    libchromatix_hi556_holitech_13m_cpp_hfr_60 \
    libchromatix_hi556_holitech_13m_cpp_hfr_90 \
    libchromatix_hi556_holitech_13m_cpp_liveshot \
    libchromatix_hi556_holitech_13m_cpp_preview \
    libchromatix_hi556_holitech_13m_cpp_snapshot \
    libchromatix_hi556_holitech_13m_cpp_us_chromatix \
    libchromatix_hi556_holitech_13m_cpp_video \
    libchromatix_hi556_holitech_13m_cpp_video_full \
    libchromatix_hi556_holitech_13m_default_video \
    libchromatix_hi556_holitech_13m_hfr_120 \
    libchromatix_hi556_holitech_13m_hfr_60 \
    libchromatix_hi556_holitech_13m_hfr_90 \
    libchromatix_hi556_holitech_13m_postproc \
    libchromatix_hi556_holitech_13m_preview \
    libchromatix_hi556_holitech_13m_snapshot \
    libchromatix_hi556_holitech_13m_video_full \
    libchromatix_hi556_holitech_13m_zsl_preview \
    libchromatix_hi556_holitech_13m_zsl_video \
    libchromatix_hi556_holitech_16m_a3_default_preview \
    libchromatix_hi556_holitech_16m_a3_default_video \
    libchromatix_hi556_holitech_16m_a3_hfr_120 \
    libchromatix_hi556_holitech_16m_a3_hfr_60 \
    libchromatix_hi556_holitech_16m_a3_hfr_90 \
    libchromatix_hi556_holitech_16m_common \
    libchromatix_hi556_holitech_16m_cpp_ds_chromatix \
    libchromatix_hi556_holitech_16m_cpp_hfr_120 \
    libchromatix_hi556_holitech_16m_cpp_hfr_60 \
    libchromatix_hi556_holitech_16m_cpp_hfr_90 \
    libchromatix_hi556_holitech_16m_cpp_liveshot \
    libchromatix_hi556_holitech_16m_cpp_preview \
    libchromatix_hi556_holitech_16m_cpp_snapshot \
    libchromatix_hi556_holitech_16m_cpp_us_chromatix \
    libchromatix_hi556_holitech_16m_cpp_video \
    libchromatix_hi556_holitech_16m_cpp_video_full \
    libchromatix_hi556_holitech_16m_default_video \
    libchromatix_hi556_holitech_16m_hfr_120 \
    libchromatix_hi556_holitech_16m_hfr_60 \
    libchromatix_hi556_holitech_16m_hfr_90 \
    libchromatix_hi556_holitech_16m_postproc \
    libchromatix_hi556_holitech_16m_preview \
    libchromatix_hi556_holitech_16m_snapshot \
    libchromatix_hi556_holitech_16m_video_full \
    libchromatix_hi556_holitech_16m_zsl_preview \
    libchromatix_hi556_holitech_16m_zsl_video \
    libchromatix_hi846_kingcome_front_a3_default_preview \
    libchromatix_hi846_kingcome_front_a3_default_video \
    libchromatix_hi846_kingcome_front_a3_hfr_120 \
    libchromatix_hi846_kingcome_front_a3_hfr_60 \
    libchromatix_hi846_kingcome_front_a3_hfr_90 \
    libchromatix_hi846_kingcome_front_common \
    libchromatix_hi846_kingcome_front_cpp_ds_chromatix \
    libchromatix_hi846_kingcome_front_cpp_hfr_120 \
    libchromatix_hi846_kingcome_front_cpp_hfr_60 \
    libchromatix_hi846_kingcome_front_cpp_hfr_90 \
    libchromatix_hi846_kingcome_front_cpp_liveshot \
    libchromatix_hi846_kingcome_front_cpp_preview \
    libchromatix_hi846_kingcome_front_cpp_snapshot \
    libchromatix_hi846_kingcome_front_cpp_us_chromatix \
    libchromatix_hi846_kingcome_front_cpp_video \
    libchromatix_hi846_kingcome_front_default_video \
    libchromatix_hi846_kingcome_front_hfr_120 \
    libchromatix_hi846_kingcome_front_hfr_60 \
    libchromatix_hi846_kingcome_front_hfr_90 \
    libchromatix_hi846_kingcome_front_liveshot \
    libchromatix_hi846_kingcome_front_postproc \
    libchromatix_hi846_kingcome_front_preview \
    libchromatix_hi846_kingcome_front_snapshot \
    libchromatix_hi846_kingcome_front_zsl_preview \
    libchromatix_hi846_kingcome_front_zsl_video \
    libchromatix_hi846_tsp_front_a3_default_preview \
    libchromatix_hi846_tsp_front_a3_default_video \
    libchromatix_hi846_tsp_front_a3_hfr_120 \
    libchromatix_hi846_tsp_front_a3_hfr_60 \
    libchromatix_hi846_tsp_front_a3_hfr_90 \
    libchromatix_hi846_tsp_front_common \
    libchromatix_hi846_tsp_front_cpp_ds_chromatix \
    libchromatix_hi846_tsp_front_cpp_hfr_120 \
    libchromatix_hi846_tsp_front_cpp_hfr_60 \
    libchromatix_hi846_tsp_front_cpp_hfr_90 \
    libchromatix_hi846_tsp_front_cpp_liveshot \
    libchromatix_hi846_tsp_front_cpp_preview \
    libchromatix_hi846_tsp_front_cpp_snapshot \
    libchromatix_hi846_tsp_front_cpp_us_chromatix \
    libchromatix_hi846_tsp_front_cpp_video \
    libchromatix_hi846_tsp_front_default_video \
    libchromatix_hi846_tsp_front_eis_video \
    libchromatix_hi846_tsp_front_hfr_120 \
    libchromatix_hi846_tsp_front_hfr_60 \
    libchromatix_hi846_tsp_front_hfr_90 \
    libchromatix_hi846_tsp_front_liveshot \
    libchromatix_hi846_tsp_front_postproc \
    libchromatix_hi846_tsp_front_preview \
    libchromatix_hi846_tsp_front_snapshot \
    libchromatix_hi846_tsp_front_zsl_preview \
    libchromatix_hi846_tsp_front_zsl_video \
    libchromatix_ov13855_chicony_rear_common \
    libchromatix_ov13855_chicony_rear_cpp_ds_chromatix \
    libchromatix_ov13855_chicony_rear_cpp_hfr_120 \
    libchromatix_ov13855_chicony_rear_cpp_hfr_60 \
    libchromatix_ov13855_chicony_rear_cpp_hfr_90 \
    libchromatix_ov13855_chicony_rear_cpp_liveshot \
    libchromatix_ov13855_chicony_rear_cpp_preview \
    libchromatix_ov13855_chicony_rear_cpp_snapshot \
    libchromatix_ov13855_chicony_rear_cpp_us_chromatix \
    libchromatix_ov13855_chicony_rear_cpp_video \
    libchromatix_ov13855_chicony_rear_cpp_video_full \
    libchromatix_ov13855_chicony_rear_default_preview_bu64297 \
    libchromatix_ov13855_chicony_rear_default_video \
    libchromatix_ov13855_chicony_rear_default_video_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_120 \
    libchromatix_ov13855_chicony_rear_hfr_120_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_60 \
    libchromatix_ov13855_chicony_rear_hfr_60_bu64297 \
    libchromatix_ov13855_chicony_rear_hfr_90 \
    libchromatix_ov13855_chicony_rear_hfr_90_bu64297 \
    libchromatix_ov13855_chicony_rear_postproc \
    libchromatix_ov13855_chicony_rear_preview \
    libchromatix_ov13855_chicony_rear_snapshot \
    libchromatix_ov13855_chicony_rear_video_full \
    libchromatix_ov13855_chicony_rear_zsl_preview_bu64297 \
    libchromatix_ov13855_chicony_rear_zsl_video_bu64297 \
    libchromatix_ov13855_holitech_13m_common \
    libchromatix_ov13855_holitech_13m_cpp_ds_chromatix \
    libchromatix_ov13855_holitech_13m_cpp_hfr_120 \
    libchromatix_ov13855_holitech_13m_cpp_hfr_60 \
    libchromatix_ov13855_holitech_13m_cpp_hfr_90 \
    libchromatix_ov13855_holitech_13m_cpp_liveshot \
    libchromatix_ov13855_holitech_13m_cpp_preview \
    libchromatix_ov13855_holitech_13m_cpp_snapshot \
    libchromatix_ov13855_holitech_13m_cpp_us_chromatix \
    libchromatix_ov13855_holitech_13m_cpp_video \
    libchromatix_ov13855_holitech_13m_cpp_video_full \
    libchromatix_ov13855_holitech_13m_default_preview_bu64297 \
    libchromatix_ov13855_holitech_13m_default_video \
    libchromatix_ov13855_holitech_13m_default_video_bu64297 \
    libchromatix_ov13855_holitech_13m_eis_video_bu64297 \
    libchromatix_ov13855_holitech_13m_hdr \
    libchromatix_ov13855_holitech_13m_hdr_3a \
    libchromatix_ov13855_holitech_13m_hdr_cpp \
    libchromatix_ov13855_holitech_13m_hfr_120 \
    libchromatix_ov13855_holitech_13m_hfr_120_bu64297 \
    libchromatix_ov13855_holitech_13m_hfr_60 \
    libchromatix_ov13855_holitech_13m_hfr_60_bu64297 \
    libchromatix_ov13855_holitech_13m_hfr_90 \
    libchromatix_ov13855_holitech_13m_hfr_90_bu64297 \
    libchromatix_ov13855_holitech_13m_postproc \
    libchromatix_ov13855_holitech_13m_preview \
    libchromatix_ov13855_holitech_13m_snapshot \
    libchromatix_ov13855_holitech_13m_video_full \
    libchromatix_ov13855_holitech_13m_zsl_preview_bu64297 \
    libchromatix_ov13855_holitech_13m_zsl_video_bu64297 \
    libchromatix_ov16880_qtech_front_common \
    libchromatix_ov16880_qtech_front_cpp_ds_chromatix \
    libchromatix_ov16880_qtech_front_cpp_hfr_120 \
    libchromatix_ov16880_qtech_front_cpp_hfr_60 \
    libchromatix_ov16880_qtech_front_cpp_hfr_90 \
    libchromatix_ov16880_qtech_front_cpp_liveshot \
    libchromatix_ov16880_qtech_front_cpp_preview \
    libchromatix_ov16880_qtech_front_cpp_snapshot \
    libchromatix_ov16880_qtech_front_cpp_us_chromatix \
    libchromatix_ov16880_qtech_front_cpp_video \
    libchromatix_ov16880_qtech_front_cpp_video_full \
    libchromatix_ov16880_qtech_front_default_preview_bu64297 \
    libchromatix_ov16880_qtech_front_default_video \
    libchromatix_ov16880_qtech_front_default_video_bu64297 \
    libchromatix_ov16880_qtech_front_eis_video_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_120 \
    libchromatix_ov16880_qtech_front_hfr_120_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_60 \
    libchromatix_ov16880_qtech_front_hfr_60_bu64297 \
    libchromatix_ov16880_qtech_front_hfr_90 \
    libchromatix_ov16880_qtech_front_hfr_90_bu64297 \
    libchromatix_ov16880_qtech_front_postproc \
    libchromatix_ov16880_qtech_front_preview \
    libchromatix_ov16880_qtech_front_snapshot \
    libchromatix_ov16880_qtech_front_video_full \
    libchromatix_ov16880_qtech_front_zsl_preview_bu64297 \
    libchromatix_ov16880_qtech_front_zsl_video_bu64297 \
    libchromatix_ov16885_holitech_16m_common \
    libchromatix_ov16885_holitech_16m_cpp_ds_chromatix \
    libchromatix_ov16885_holitech_16m_cpp_hfr_120 \
    libchromatix_ov16885_holitech_16m_cpp_hfr_60 \
    libchromatix_ov16885_holitech_16m_cpp_hfr_90 \
    libchromatix_ov16885_holitech_16m_cpp_liveshot \
    libchromatix_ov16885_holitech_16m_cpp_preview \
    libchromatix_ov16885_holitech_16m_cpp_snapshot \
    libchromatix_ov16885_holitech_16m_cpp_us_chromatix \
    libchromatix_ov16885_holitech_16m_cpp_video \
    libchromatix_ov16885_holitech_16m_cpp_video_full \
    libchromatix_ov16885_holitech_16m_default_preview_bu64297 \
    libchromatix_ov16885_holitech_16m_default_video \
    libchromatix_ov16885_holitech_16m_default_video_bu64297 \
    libchromatix_ov16885_holitech_16m_eis_video_bu64297 \
    libchromatix_ov16885_holitech_16m_hdr \
    libchromatix_ov16885_holitech_16m_hdr_3a \
    libchromatix_ov16885_holitech_16m_hdr_cpp \
    libchromatix_ov16885_holitech_16m_hfr_120 \
    libchromatix_ov16885_holitech_16m_hfr_120_bu64297 \
    libchromatix_ov16885_holitech_16m_hfr_60 \
    libchromatix_ov16885_holitech_16m_hfr_60_bu64297 \
    libchromatix_ov16885_holitech_16m_hfr_90 \
    libchromatix_ov16885_holitech_16m_hfr_90_bu64297 \
    libchromatix_ov16885_holitech_16m_postproc \
    libchromatix_ov16885_holitech_16m_preview \
    libchromatix_ov16885_holitech_16m_snapshot \
    libchromatix_ov16885_holitech_16m_video_full \
    libchromatix_ov16885_holitech_16m_zsl_preview_bu64297 \
    libchromatix_ov16885_holitech_16m_zsl_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_common \
    libchromatix_ov16885_ofilm_16m_cpp_ds_chromatix \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_120 \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_60 \
    libchromatix_ov16885_ofilm_16m_cpp_hfr_90 \
    libchromatix_ov16885_ofilm_16m_cpp_liveshot \
    libchromatix_ov16885_ofilm_16m_cpp_preview \
    libchromatix_ov16885_ofilm_16m_cpp_snapshot \
    libchromatix_ov16885_ofilm_16m_cpp_us_chromatix \
    libchromatix_ov16885_ofilm_16m_cpp_video \
    libchromatix_ov16885_ofilm_16m_cpp_video_full \
    libchromatix_ov16885_ofilm_16m_default_preview_bu64297 \
    libchromatix_ov16885_ofilm_16m_default_video \
    libchromatix_ov16885_ofilm_16m_default_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_eis_video_bu64297 \
    libchromatix_ov16885_ofilm_16m_hdr \
    libchromatix_ov16885_ofilm_16m_hdr_3a \
    libchromatix_ov16885_ofilm_16m_hdr_cpp \
    libchromatix_ov16885_ofilm_16m_hfr_120 \
    libchromatix_ov16885_ofilm_16m_hfr_120_bu64297 \
    libchromatix_ov16885_ofilm_16m_hfr_60 \
    libchromatix_ov16885_ofilm_16m_hfr_60_bu64297 \
    libchromatix_ov16885_ofilm_16m_hfr_90 \
    libchromatix_ov16885_ofilm_16m_hfr_90_bu64297 \
    libchromatix_ov16885_ofilm_16m_postproc \
    libchromatix_ov16885_ofilm_16m_preview \
    libchromatix_ov16885_ofilm_16m_snapshot \
    libchromatix_ov16885_ofilm_16m_video_full \
    libchromatix_ov16885_ofilm_16m_zsl_preview_bu64297 \
    libchromatix_ov16885_ofilm_16m_zsl_video_bu64297 \
    libchromatix_ov8856_chicony_front_a3_default_preview \
    libchromatix_ov8856_chicony_front_a3_default_video \
    libchromatix_ov8856_chicony_front_a3_hfr_120 \
    libchromatix_ov8856_chicony_front_a3_hfr_60 \
    libchromatix_ov8856_chicony_front_a3_hfr_90 \
    libchromatix_ov8856_chicony_front_common \
    libchromatix_ov8856_chicony_front_cpp_ds_chromatix \
    libchromatix_ov8856_chicony_front_cpp_hfr_120 \
    libchromatix_ov8856_chicony_front_cpp_hfr_60 \
    libchromatix_ov8856_chicony_front_cpp_hfr_90 \
    libchromatix_ov8856_chicony_front_cpp_liveshot \
    libchromatix_ov8856_chicony_front_cpp_preview \
    libchromatix_ov8856_chicony_front_cpp_snapshot \
    libchromatix_ov8856_chicony_front_cpp_us_chromatix \
    libchromatix_ov8856_chicony_front_cpp_video \
    libchromatix_ov8856_chicony_front_default_video \
    libchromatix_ov8856_chicony_front_eis_video \
    libchromatix_ov8856_chicony_front_hfr_120 \
    libchromatix_ov8856_chicony_front_hfr_60 \
    libchromatix_ov8856_chicony_front_hfr_90 \
    libchromatix_ov8856_chicony_front_liveshot \
    libchromatix_ov8856_chicony_front_postproc \
    libchromatix_ov8856_chicony_front_preview \
    libchromatix_ov8856_chicony_front_snapshot \
    libchromatix_ov8856_chicony_front_zsl_preview \
    libchromatix_ov8856_chicony_front_zsl_video \
    libdepthmapwrapper \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmcamera_arcsoftbokeh_lib \
    libmmcamera_bokeh \
    libmmcamera_dbg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_gc5025_ofilm_13m \
    libmmcamera_gc5025_ofilm_13m_fm24c64d_eeprom \
    libmmcamera_gc5025_ofilm_16m \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hi1333_ofilm_13m \
    libmmcamera_hi1333_ofilm_13m_fm24c64d_eeprom \
    libmmcamera_hi556_holitech_13m \
    libmmcamera_hi556_holitech_13m_fm24c64d_eeprom \
    libmmcamera_hi556_holitech_16m \
    libmmcamera_hi846_kingcome_front \
    libmmcamera_hi846_tsp_front \
    libmmcamera_hi846_tsp_front_eeprom \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_ov13855 \
    libmmcamera_ov13855_chicony_rear \
    libmmcamera_ov13855_chicony_rear_fm24c64d_eeprom \
    libmmcamera_ov13855_holitech_13m \
    libmmcamera_ov13855_holitech_13m_fm24c64d_eeprom \
    libmmcamera_ov16880_qtech_front \
    libmmcamera_ov16880_qtech_front_fm24c64d_eeprom \
    libmmcamera_ov16880_qtech_rear \
    libmmcamera_ov16885_holitech_16m \
    libmmcamera_ov16885_holitech_16m_fm24c64d_eeprom \
    libmmcamera_ov16885_ofilm_16m \
    libmmcamera_ov16885_ofilm_16m_fm24c64d_eeprom \
    libmmcamera_ov8856 \
    libmmcamera_ov8856_2lane \
    libmmcamera_ov8856_4lane \
    libmmcamera_ov8856_chicony_front \
    libmmcamera_ov8856_chicony_front_eeprom \
    libmmcamera_ov8856b_chicony_front \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmorpho_video_refiner \
    libmpbase \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    cdfinger.fingerprint.default \
    fingerprint.sdm660 \
    libgf_ca \
    libgf_hal \
    libqfp-service \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    libvendor.goodix.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fingerprint-V1.0-java \
    qfp-daemon \
    sensors.qti

PRODUCT_PACKAGES += \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so
